# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3e1244c277c7497b392dd7d012397c54c29a1b663ee196b79f238439d787d5642379ad1b891ff10b42f07fc46933296e8ddbffc423c267b67c3fdc69c41e05

test:
  secret_key_base: 0385068501d4199e6669b3e0ec623d588cd0b65e8d321f6be6cd38fc52bce4c20230599866e89d6c97d756472be5ec93a06b630a1e58fda95d8dd9258120d39e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
